#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time
import sys

# Morse code dictionary
morse_code = {
    'a': '.-', 'b': '-...', 'c': '-.-.', 'd': '-..', 'e': '.',
    'f': '..-.', 'g': '--.', 'h': '....', 'i': '..', 'j': '.---',
    'k': '-.-', 'l': '.-..', 'm': '--', 'n': '-.', 'o': '---',
    'p': '.--.', 'q': '--.-', 'r': '.-.', 's': '...', 't': '-',
    'u': '..-', 'v': '...-', 'w': '.--', 'x': '-..-', 'y': '-.--',
    'z': '--..', '1': '.----', '2': '..---', '3': '...--',
    '4': '....-', '5': '.....', '6': '-....', '7': '--...',
    '8': '---..', '9': '----.', '0': '-----', '.': '.-.-.-',
    ',': '--..--', '?': '..--..', '!': '-.-.--', '-': '-....-', '/': '-..-.',
    '@': '.--.-.', '(': '-.--.', ')': '-.--.-'
}

# Setup GPIO
LED_PIN = 17
GPIO.setmode(GPIO.BCM)
GPIO.setup(LED_PIN, GPIO.OUT)

# TIME_UNIT = 0.05
TIME_UNIT = 0.01



def send_message(message):
    for s in message:
        if s == ' ':
            time.sleep(7 * TIME_UNIT) # space between words
            continue
        for c in morse_code[s]:
            GPIO.output(LED_PIN, GPIO.HIGH)
            if c == '-':
                time.sleep(3 * TIME_UNIT) # dash is 3x dot
            else:
                time.sleep(TIME_UNIT) # dot
            GPIO.output(LED_PIN, GPIO.LOW)
            time.sleep(TIME_UNIT) # space between dot/dash

        time.sleep(3 * TIME_UNIT) # space between letters


if __name__ == '__main__':
    try:
        repeats = int(sys.argv[1])
        message = sys.argv[2].lower()
        for _ in range(repeats):
            send_message(message)
            time.sleep(10 * TIME_UNIT) # space between repeats

    except IndexError:
        print("Usage: ./send <repeats> \"<message>\"")
    except KeyboardInterrupt:
        print("Program exited")
    finally:
        GPIO.cleanup()

